### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by nagyrobi** [zuidwijk/dsmr#10]
Hi! I have a few questions.

1. In the config what do I have to put if I still want to use the normal RX pin of Wemos, and not D7? (I already build my hardware like [this](https://tasmota.github.io/docs/_media/p1-smartmeter/p1-smartmeter_v2.png) 6 months ago, I don't use the USB connection at all)
```
uart:
  baud_rate: 115200
  rx_pin: ??
```

2. What info do you need to add support for ELMŰ energy provider in Budapest? I have a [description](https://elmuhalozat.hu/elmu/file/downloadfile?id=e17e5c5b-88df-4282-bbd6-856457a41582), see from page 13 onwards. Currently working with Tasmota based on [this](https://tasmota.github.io/docs/Smart-Meter-Interface/#sanxing-sx6x1-sxxu1x-ascii-obis) but I'd give it a spin with ESPhome and your solution. Can provide fresh sample data if you want.

**Comment by zuidwijk** [comment]
Rx is GPIO03:
![esp8266-wemos-d1-mini-pinout](https://user-images.githubusercontent.com/10123063/128414234-34982938-34a2-42c1-b18e-faae23400f4b.png)

If you don't specify a rx, it will uses the default... 

Here more information:
https://esphome.io/components/uart.html?highlight=uart

For ELMU, we have to look at the used OBIS tags (page 11). Probably most will be te same. We have to look for the differences.

**Comment by nagyrobi** [comment]
I was asking for the RX syntax because I noticed that ESPhome uses Dx pin notations too and I was confused if it was accepting GPIOx names or not for the pins, thanks for clarification.

Thanks in advance for looking up the ELMŰ codes and adding to the project also the way to enable them.

**Comment by klaasnicolaas** [comment]
Maybe open a different issue for the ELMŰ support 😉
