### ISSUE TITLE
Built-in Support for DSMR 2.2

### ISSUE THREAD

**Issue by michielappelman** [zuidwijk/dsmr#12]
To support DSMR version 2.2 it seems that at least two changes will need to be made to the component code, and a smaller changes to the ESPHome YAML file.

If DSMR 2.2/3.0 support is something you'd like to support, these notes below could potentially help. To really solve this, I reckon the following steps should be taken:

- [ ] Document UART settings for different DSMR versions
- [ ] Enable skipping of CRC checks on P1 telegrams
- [ ] Add field definition (parsed or not) for lines with just a value (lacking an Obis ID)

## Set correct UART mode

To start with the easy part: getting the SlimmeLezer to read the messages for DSMR 2.2 and 3.0 the UART block will need to be changed as follows: 

```yaml
uart:
  baud_rate: 9600
  rx_pin: D7
  data_bits: 7
  parity: EVEN
  stop_bits: 1
```

This also required me to disable the logging on the UART channel:

```yaml
logger:
  baud_rate: 0
```

## Disable the CRC check

Since CRCs are not present in DSMR 2.2, I have removed all the references to the CRC check methods in the `P1Parser` of the `parser.h` file:

```diff
     // Look for ! that terminates the data
     const char *data_end = data_start;
-    uint16_t crc = _crc16_update(0, *str);  // Include the / in CRC
     while (data_end < str + n && *data_end != '!') {
-      crc = _crc16_update(crc, *data_end);
       ++data_end;
     }

-    if (data_end >= str + n)
-      return res.fail(F("No checksum found"), data_end);
-
-    crc = _crc16_update(crc, *data_end);  // Include the ! in CRC
-
-    ParseResult<uint16_t> check_res = CrcParser::parse(data_end + 1, str + n);
-    if (check_res.err)
-      return check_res;
-
-    // Check CRC
-    if (check_res.result != crc) {
-      Serial.println(check_res.result);
-      Serial.println(crc);
-
-      return res.fail(F("Checksum mismatch"), data_end + 1);
-    }
-
     res = parse_data(data, data_start, data_end, unknown_error);
-    res.next = check_res.next;
+    res.next = data_end;
     return res;
   }
```

## Skip data lines that contain nothing but values

I then got some errors saying:

```
[15:16:58][E][dsmr:137]: (09825.905)
^
OBIS id Empty
```

This was apparently caused by a line without any Obis ID (well, duh) but apparently this is valid in DSMR 2.2? I manually skipped over these lines in the parser function for Data Lines:

```diff
   template<typename Data>
   static ParseResult<void> parse_line(Data *data, const char *line, const char *end, bool unknown_error) {
     ParseResult<void> res;
+    if (*line == '(')
+      return res;
     if (line == end)
       return res;
```

**Comment by michielappelman** [comment]
Looking into this a bit more, it seems that the second point has been an 'upstream' issue with a PR for some time: [matthijskooijman/arduino-dsmr#18](https://github.com/matthijskooijman/arduino-dsmr/pull/18). Perhaps it is time to get this integrated.

The last point regarding missing Obis IDs, has also been known for some time, see [matthijskooijman/arduino-dsmr#22](https://github.com/matthijskooijman/arduino-dsmr/issues/22).

For your reference, my full telegram included below:

```
/XMX5XMXABCD100003637

0-0:96.1.1(4B383257303039373436303131313131)
1-0:1.8.1(15444.442*kWh)
1-0:1.8.2(17017.423*kWh)
1-0:2.8.1(00000.000*kWh)
1-0:2.8.2(00000.000*kWh)
0-0:96.14.0(0002)
1-0:1.7.0(0000.31*kW)
1-0:2.7.0(0000.00*kW)
0-0:96.13.1()
0-0:96.13.0()
0-1:96.1.0(3238303131303031313434333035383131)
0-1:24.1.0(03)
0-1:24.3.0(210809130000)(08)(60)(1)(0-1:24.2.0)(m3)
(09828.522)
!
```

 1) OBIS Reduced ID-code – **0-1:24.3.0**
 2) Time Stamp (TST12) of oldest measurement value(s)m, RP1  – **210809130000**
 3) Profile Status Sn. – **08**
 4) Recording Period in Minutes.(capture period attribute). – **60**
 5) Number of measurement values z. – **1**
 6) Identifications of measurement values (OBIS Reduced ID codes of capture objects attribute) – **0-1:24.2.0**
 7) Units of measurement values (Units of capture_objects attribute) – **m3**
 8) Measurement value 1 (entry 1 of buffer attribute without unit) – **09828.522**

Not sure why an extra carriage return/line feed is inserted between 7 and 8, but it is what it is. Seems other parsers have also had to deal with this. See:

 - [lvzon/dsmr-p1-parser](https://github.com/lvzon/dsmr-p1-parser/blob/master/p1-parser.rl#L562)
 - [ndokter/dsmr_parser](https://github.com/ndokter/dsmr_parser/blob/master/dsmr_parser/obis_references.py#L47)

**Comment by zuidwijk** [comment]
Just tested it with a customer, this indeed works!

For those who needed, I've compiled it with the latest esphome-dev code:
[slimmelezer-dsmr2.2.bin.zip](https://github.com/zuidwijk/dsmr/files/6956771/slimmelezer-dsmr2.2.bin.zip)

I won't update the code for now, as most meters are either DSMR 4 or 5.

**Comment by michielappelman** [comment]
I have created a DSMR version 2.2 and 3.0 specific fork at https://github.com/michielappelman/dsmr

**Comment by jurjenoskam** [comment]
@zuidwijk Is there any significant downside to introducing compatibility with DSMR2? The SlimmeLezer I ordered does not work on my smart meter, since it's DSMR2.2+. I have to use the binary you compiled, or michielappelmans fork.

My meter uses the following serial parameters:

  baud_rate: 9600
  data_bits: 7
  parity: EVEN
  stop_bits: 1

...and it sends the following telegram every 10 seconds:

```
/XMX5XMXABCE000035164

0-0:96.1.1(31333031333735352020202020202020)
1-0:1.8.1(21599.791*kWh)
1-0:1.8.2(22282.132*kWh)
1-0:2.8.1(03818.926*kWh)
1-0:2.8.2(09457.169*kWh)
0-0:96.14.0(0001)
1-0:1.7.0(0000.00*kW)
1-0:2.7.0(0000.40*kW)
0-0:96.13.1()
0-0:96.13.0()
0-1:96.1.0(3238303131303038323238303732393132)
0-1:24.1.0(03)
0-1:24.3.0(210815090000)(08)(60)(1)(0-1:24.2.0)(m3)
(11785.723)
!
```

**Comment by zuidwijk** [comment]
> @zuidwijk Is there any significant downside to introducing compatibility with DSMR2? The SlimmeLezer I ordered does not work on my smart meter, since it's DSMR2.2+. I have to use the binary you compiled, or michielappelmans fork.
> 
> My meter uses the following serial parameters:
> 
> baud_rate: 9600
> data_bits: 7
> parity: EVEN
> stop_bits: 1
> 
> ...and it sends the following telegram every 10 seconds:
> 
> ```
> /XMX5XMXABCE000035164
> 
> 0-0:96.1.1(31333031333735352020202020202020)
> 1-0:1.8.1(21599.791*kWh)
> 1-0:1.8.2(22282.132*kWh)
> 1-0:2.8.1(03818.926*kWh)
> 1-0:2.8.2(09457.169*kWh)
> 0-0:96.14.0(0001)
> 1-0:1.7.0(0000.00*kW)
> 1-0:2.7.0(0000.40*kW)
> 0-0:96.13.1()
> 0-0:96.13.0()
> 0-1:96.1.0(3238303131303038323238303732393132)
> 0-1:24.1.0(03)
> 0-1:24.3.0(210815090000)(08)(60)(1)(0-1:24.2.0)(m3)
> (11785.723)
> !
> ```

And does that work? The compiled version I've placed?

At this moment we're looking into the option to use one code, and there specify what type dsmr reader you have. Yet that's not ready yet. So this special bin file is a temporary patch to make sure you can use the reader.

**Comment by jurjenoskam** [comment]
> And does that work? The compiled version I've placed?
>
> At this moment we're looking into the option to use one code, and there specify what type dsmr reader you have. Yet that's not ready yet. So this special bin file is a temporary patch to make sure you can use the reader.

The compiled version you placed works fine for electricity, but for gas the value is not properly parsed (likely due to the weird newline in the telegram). The value of the field is:

```
(210818160000)(08)(60)(1)(0-1:24.2.0)(m3)
(11785.976) 
```
