### ISSUE TITLE
Belgium telegrams aren't recognized

### ISSUE THREAD

**Issue by klenaers** [zuidwijk/dsmr#14]
Hi,

I noticed that the telegram from Fluvius weren't recognized and gave an error. This was also wrong in the original dsmr-project.

I changed following lines in the fields.h and everything started working.

```
/* Instantaneous current L1 in A resolution */
//DEFINE_FIELD(current_l1, uint16_t, ObisId(1, 0, 31, 7, 0), IntField, units::A);
DEFINE_FIELD(current_l1, FixedValue, ObisId(1, 0, 31, 7, 0), FixedField, units::A, units::mA);
/* Instantaneous current L2 in A resolution */
//DEFINE_FIELD(current_l2, uint16_t, ObisId(1, 0, 51, 7, 0), IntField, units::A);
DEFINE_FIELD(current_l2, FixedValue, ObisId(1, 0, 51, 7, 0), FixedField, units::A, units::mA);
/* Instantaneous current L3 in A resolution */
//DEFINE_FIELD(current_l3, uint16_t, ObisId(1, 0, 71, 7, 0), IntField, units::A);
DEFINE_FIELD(current_l3, FixedValue, ObisId(1, 0, 71, 7, 0), FixedField, units::A, units::mA);
```

**Comment by zuidwijk** [comment]
Nice job! I'll share this with @glmnet and Otto to see if they've changed it too at their side

**Comment by zuidwijk** [comment]
@klenaers : Can you post a full telegram from your meter? If tested previous code on Belgium meters and though the meter is DSMR 5, the obis code (telegram) was saying 4.2 (and 1 package each 10 seconds). Now I assume it's upgraded and therefore I want to compare some more code.

**Comment by zuidwijk** [comment]
Tested it on my reader and the fix still works, so shouldn't be any issue.

**Comment by zuidwijk** [comment]
Will be pulled
#15

**Comment by klenaers** [comment]
@zuidwijk This is the current telefram and it's sent every second. Thank you for the update.

/FLU5\253769484_A

0-0:96.1.4(50215)
0-0:96.1.1(3153414733313030323235333936)
0-0:1.0.0(210807232019S)
1-0:1.8.1(000584.535*kWh)
1-0:1.8.2(000877.164*kWh)
1-0:2.8.1(001100.756*kWh)
1-0:2.8.2(000439.050*kWh)
0-0:96.14.0(0002)
1-0:1.7.0(00.294*kW)
1-0:2.7.0(00.000*kW)
1-0:21.7.0(00.021*kW)
1-0:41.7.0(00.050*kW)
1-0:61.7.0(00.221*kW)
1-0:22.7.0(00.000*kW)
1-0:42.7.0(00.000*kW)
1-0:62.7.0(00.000*kW)
1-0:32.7.0(238.7*V)
1-0:52.7.0(237.6*V)
1-0:72.7.0(236.7*V)
1-0:31.7.0(000.49*A)
1-0:51.7.0(000.41*A)
1-0:71.7.0(001.68*A)
0-0:96.3.10(1)
0-0:17.0.0(999.9*kW)
1-0:31.4.0(999*A)
0-0:96.13.0()
0-1:24.1.0(003)
0-1:96.1.1(37464C4F32313230303730393130)
0-1:24.4.0(1)
0-1:24.2.3(210807232005S)(00590.815*m3)
!8FA5
