### ISSUE TITLE
Aidon Sweden support

### ISSUE THREAD

**Issue by robwiklu** [zuidwijk/dsmr#18]
Dear devs,

I've learned that my Slimme Lezer does not support the meter Aidon 6442SE. Here is more information about the HAN port and data streams from it: https://www.skekraft.se/wp-content/uploads/2021/03/Aidon_Feature_Description_RJ12_HAN_Interface_EN.pdf
The reason no data comes out to the Slimme Lezer is probably because Aidon not fully follows the standards - it encapsulates the data in a HDLC frame.

But, here are some help for the developers:
https://github.com/aviborg/esp-smart-meter
https://github.com/aviborg/swedishP1

Please contact the above maintainer, I'm sure you coult get it working on the Slimme Lezer.

**Comment by zuidwijk** [comment]
Hi Rob,

I will close this issue, as all development goes with esphome itself (in version 2021.8.0)
