### ISSUE TITLE
Installation instructions

### ISSUE THREAD

**Issue by rmjjanssen1** [zuidwijk/dsmr#20]
Hi Marcel,

I try to add your wonderful slimmelezer project to my Home Assistant setup, but somehow I cannot get it done. This is what I did so far

1) (pre-)Flash and ESP8266 (Wemos D1) using ESPHome flasher (on my computer) with the (latest) SlimmeLezer firmware downloaded from your website.
Installed the ESP home plugin to Home assistant
Once the ESP device is flashed, I was able to connect to ESP slimmelezer AP to configure the Wifi credentials, It connects to the Wifi network and also able to access the local webGUI by browsing to the locally assigned IP address

At this point I get stuck; I was expecting that the preflashed esp device to show up in the ESP home dashboard but somehow it is not 'auto discovered'.  When I add a 'new node', it seems you start off with a 'empty' precompiled version of ESP home on the device so not doing what I want to do. 

Can you assist or point me to the installation instructions?; somehow I cannot find these on your website!

Thanks!

**Comment by glmnet** [comment]
Esphome dashboard does not detects devices, you have to create them and you can use the code from this repo. The yaml file. Then try to install that yaml using esphome dashboard. 

Home assistant does auto detect esphome devices as integrations. This should happen either if you install a precompiled firmware or if you compile and install a firmware with the esphome dashboard. 
If home assistant doesn't detect you can go and add a new esphome integration and enter the device address manually

**Comment by rmjjanssen1** [comment]
Hi,

Found it, indeed I was looking at the wrong place in home assistant. Precompiled version show up on the integration dashboard in HA. So the steps are

1) Install ESP home Add-on in HA
2)Download the precompiled slimmelezer firmware from this Git
3) Flash it with ESPHome-flasher
4) Reset the device and wait until it appears as WiFi AP (I found it under SSID slimmelezer)
5) Connect to the slimmelezer AP and wait until a window pops-up. Here you can fill in the WiFi credentials of your home WiFi network
6) Wait until the device connects to your WiFi network (reset it is not appearing). I checked this by logging in on my modem and see if it appears in the 'network overview'. Here you can also find the locally assigned IP address
7) Go to HA integration page and see if the device is recognised. Install/add it when it appears as discovered integration
8) Your done.  Now you should be able to see it as a device with a number of entities and can start adding it to HA energy

**Comment by zuidwijk** [comment]
Please add any issue to the ESPHome GitHub, there the component will be maintained.
