### ISSUE TITLE
Belgian Sagemcom T211 invalid string length error

### ISSUE THREAD

**Issue by PietPetrus** [zuidwijk/dsmr#21]
After receiving my package, I immediately opened the ports on my digital meter. The setup was super easy and quick but alas I get an error stating:

Invalid string length
[E][dsmr:138]: 0-0:96.1.4(xxxxx)

I already did an OTA update with the latest version available on the product page! (To be sure)

Can I resolve this myself by editing a config file?

Thanks in advance!

**Comment by Zebber** [comment]
I'm having the same issue, followed the same steps. Complete error is:
> [E][dsmr:138]: 0-0:96.1.4(50215)
>            ^
> Invalid string length

The digital meter itself is branded "Siconia", but googling it, it looks exactly the same as the OP, so I'm guessing the same issue, and there will be more people like us too.

**Comment by zuidwijk** [comment]
Please add any issue to the ESPHome GitHub, there the component will be maintained.
