### ISSUE TITLE
Gas Consumed empty

### ISSUE THREAD

**Issue by TopdRob** [zuidwijk/dsmr#7]
Hi Marcel,

My Gas Consumed is empty. I've read my telegram and for example my gas is in 0-2:24.2.1
When I look in fields.h the GAS_MBUS_ID is 1 but in my case it should be 2

https://github.com/zuidwijk/dsmr/blob/11e86854b1a00762fdf53f36a58db1393aabb53b/components/dsmr/fields.h#L176

https://github.com/zuidwijk/dsmr/blob/11e86854b1a00762fdf53f36a58db1393aabb53b/components/dsmr/fields.h#L330-L346

Is it possible to fix this?

**Comment by zuidwijk** [comment]
Hi TopdRob,

I know exactly what you mean. I've asked some esphome dev-ers for a clean solution. In this case, I'd like to make the GAS_MBUS_ID configurable in the yaml file itself. Personally I'm not sure if that's technically possible, but would be the cleanest solution.

Obviously you could download the code and make a custom_component of it (quick solution) and change the id for yourself.

I'll let you know :)

**Comment by TopdRob** [comment]
DSMR reader had the same issue https://github.com/dsmrreader/dsmr-reader/issues/778
and they seems to pick always the last one.

https://github.com/dsmrreader/dsmr-reader/blob/5a845e29e17151be77b0393e70ba437c449535a7/dsmr_parser/parsers.py#L41-L50

**Comment by bakboord4** [comment]
Filed the same issue under: https://github.com/esphome/issues/issues/2327.
Bit unclear who is the owner, using the slimmelezer hardware, a modified slimmerlezer.yaml from Marcel Zuidwijk and ESPHome internal component DSMR.

**Comment by zuidwijk** [comment]
The dsmr component is "my" component. Yet I'm not a coder and payed a Dev-er to write it. Yet maintaining code on more than one location isn't efficient. Now I'm focusing on all the backorders to be produced and sent to customers. Latest changes are done in the code off @glmnet and now finally into ESPHome core. My wish is to get that specific code leading (the ESPHome core). That was my main goal 😉

**Comment by jesserockz** [comment]
Hello, as @bakboord4 has done, please report any ESPHome DSMR component issues to the ESPHome issue tracker. This external component will most likely not be kept up to date with the "native" code and should be deleted to remove confusion.

**Comment by zuidwijk** [comment]
With what Jesse says, please go to the DSMR component within ESPHome for support or extra features.
I will close this issue, as all development goes with esphome itself (in version 2021.8.0)
