### ISSUE TITLE
SlimmeLezer entity not appearing in "Grid Consumption" part of Home Assistant (Energy tab)

### ISSUE THREAD

**Issue by ovitters** [zuidwijk/dsmr#9]
Hi,

In brief: the SlimmeLezer doesn't appear in the dropdown list for the Grid Consumption part of HA (Energy tab), which is new for HA 2021.8.

I tried figuring out the how everything in Home Assistant interacts, but failed (too many components). I'm not sure where the cause is, might be another project. As I don't know what's relevant, I tried to include anything that you might want to know.

I bought the Slimme Lezer on Monday. I then used my mobile to connect to its WiFi, then set the WiFi, then it appeared in Home Assistant (which isn't on WiFi). It shows up under Integrations as "ESPHome". The entities itself seem ok (e.g. I can see kWh, etc).

![image](https://user-images.githubusercontent.com/673889/128179504-0bb73b35-65d8-43c5-94b4-d2cc43667bf2.png)

It won't show up if I try to configure the Energy bit and try to add it under "Consumed Energy", see below screenshot. The things that show up are my Zigbee plugs that also do energy monitoring.

![image](https://user-images.githubusercontent.com/673889/128179927-9479482d-0830-4578-b2a5-fe54fc39d8ba.png)

If I click on "Why is my entity not listed", it points to the following bit:
https://www.home-assistant.io/more-info/statistics/

Which seem to indicate a few entities need state_class set to measurement. If I check the entities that do show up (NOT from SlimmeLezer), that's what they also list. For example, for one of my plugs it shows (Developer Tools):
```
state_class: measurement
last_reset: '1970-01-01T00:00:00+00:00'
current: 0
energy: 0.42
last_seen: '2021-08-04T12:23:55.049Z'
linkquality: 54
power: 0
power_outage_memory: null
voltage: 227
unit_of_measurement: kWh
friendly_name: XXX_energy
device_class: energy
```

If I check one of the likely SlimmeLezer entities that probably should've appeared under "Grid Consumption", I see the following (Developer Tools):
```
unit_of_measurement: kWh
friendly_name: Energy Consumed Tariff 1
device_class: energy
```

I tried figuring out where "device_class: energy" is set, but failed (basically anywhere I found this, it also had state_class: measurement).

Or (thinking as I write this issue) should I maybe manually configure some kind of entity which combines "Energy Consumed Tariff 1" and "Energy Consumed Tariff 2"?

Note: I configured this while running the HA 2021.8 beta version (beta 9 I think). I didn't want to wait for 2021.8.

Thanks for making the SlimmeLezer and shipping it so quickly! Oh, Dutch/English, either is ok.

**Comment by klaasnicolaas** [comment]
I'm experiencing the same problem, we are investigating what cause this problem. Because #6 should add support for the new energy features in Home Assistant.

**Comment by lucasfijen** [comment]
Same problem here,

I seem to have found a temporary fix by adding manual sensors in my configuration.yaml

```yaml
utility_meter:
  energy_day_tariff_1:
    source: sensor.energy_consumed_tariff_1
    cycle: daily
  energy_day_tariff_2:
    source: sensor.energy_consumed_tariff_2
    cycle: daily
```

I didn't test it yet long enough to check if the values won't be a mess after the cycle ends, so please double check that in a day:)

**Comment by klaasnicolaas** [comment]
Update ESPHome to `1.20.4` and update your slimmelezer, it should be fixed now 😉

**Comment by ovitters** [comment]
For those like me who never used ESPHome before, this is how to fix it:

1. In the Supervisor Store, add ESPHome: https://my.home-assistant.io/redirect/supervisor_addon_store/. In case the Supervisor Addon Store doesn't have 1.20.4: "ha addons reload" seems to force to check for updates. Use a Terminal addon to run that command if needed. Or just wait.
2. Make sure to start the ESPHome addon, plus (optional but easier) show it in the sidebar
3. Detemine the exact service name for the existing "slimmelezer-XXXX" (including the XXX) (I'm not sure about needing the exact name, seems my device has the XXX twice now!)
4. Go to ESPHome in HA, click the "+" button. As name, fill in the exact name from step 3. Then fill in your WiFi details. Click next, then choose "ESP8266", click Next again.
5. On the top right part of the ESPHome screen press the "..." menu and choose "Secrets Editor". Add something like the following:
```
wifi_ssid: YourWiFiName
wifi_password: "SuperSecretPassword"

```
6. Now go to the device, choose "Edit", then copy paste the contents of the following link in there (so NOT the link, what is shown in the link): https://raw.githubusercontent.com/zuidwijk/dsmr/main/slimmelezer.yaml  (so the contents of slimmelezer.yaml in this repository).
7. In slimmelezer.yaml, I adjusted device_name to "slimmelezer-XXXX" (as found before). I now have slimmelezer-XXX-XXX, so one of these steps isn't the right step!
8. Save it
9. Click install and hope for the best (it worked for me, aside from it being named -XXX-XXX now)!

I now have the following in Developer Tools:
```
state_class: measurement
last_reset: '1970-01-01T00:00:00+00:00'
unit_of_measurement: kWh
friendly_name: Energy Consumed Tariff 1
device_class: energy
```

**Comment by glmnet** [comment]
> 2\. In slimmelezer.yaml, I adjusted device_name to "slimmelezer-XXXX" (as found before). I now have slimmelezer-XXX-XXX, so one of these steps isn't the right step!

Thanks for the explanation! Please edit and add a note to remove this directive `name_add_mac_suffix: true` from your new file to prevent the extra `-XXX`

**Comment by ovitters** [comment]
> Thanks for the explanation! Please edit and add a note to remove this directive `name_add_mac_suffix: true` from your new file to prevent the extra `-XXX`

Ah, so the simplest instructions are to just not change anything in the yaml. I did add a warning on why the device name shouldn't be changed.

Note: Though the issue is fixed it seems good to keep this issue open for a while so people can see how to fix it.

**Comment by klaasnicolaas** [comment]
Since it's solved, I say case closed.
If someone has a new problem with the slimmelezer, please open a new issue.
